INSERT INTO territory (territory_id, name, population, parent_id) VALUES (1, 'Guatemala', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (2, 'El Progreso', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (3, 'Sacatepéquez', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (4, 'Chimaltenango', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (5, 'Escuintla', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (6, 'Santa Rosa', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (7, 'Sololá', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (8, 'Totonicapán', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (9, 'Quetzaltenango', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (10, 'Suchitepéquez', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (11, 'Retalhuleu', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (12, 'San Marcos', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (13, 'Huehuetenango', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (14, 'Quiché', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (15, 'Baja Verapaz', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (16, 'Alta Verapaz', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (17, 'Petén', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (18, 'Izabal', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (19, 'Zacapa', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (20, 'Chiquimula', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (21, 'Jalapa', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (22, 'Jutiapa', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (23, 'Guatemala', 1229215, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (24, 'Santa Catarina Pinula', 88047, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (25, 'San José Pinula', 90835, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (26, 'San José del Golfo', 8545, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (27, 'Palencia', 75417, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (28, 'Chinautla', 126289, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (29, 'San Pedro Ayampuc', 69948, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (30, 'Mixco', 538189, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (31, 'San Pedro Sacatepéquez', 58175, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (32, 'San Juan Sacatepéquez', 291199, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (33, 'San Raymundo', 39162, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (34, 'Chuarrancho', 17436, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (35, 'Fraijanes', 65302, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (36, 'Amatitlán', 156177, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (37, 'Villa Nueva', 501127, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (38, 'Villa Canales', 169534, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (39, 'San Miguel Petapa', 154729, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (40, 'Guastatoya', 27803, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (41, 'Morazán', 12736, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (42, 'San Agustín Acasaguastlán', 56428, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (43, 'San Cristóbal Acasaguastlán', 8055, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (44, 'El Jícaro', 13539, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (45, 'Sansare', 13812, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (46, 'Sanarate', 42840, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (47, 'San Antonio La Paz', 22916, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (48, 'Antigua Guatemala', 61360, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (49, 'Jocotenango', 24463, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (50, 'Pastores', 20445, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (51, 'Sumpango', 48564, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (52, 'Santo Domingo Xenacoj', 15476, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (53, 'Santiago Sacatepéquez', 38667, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (54, 'San Bartolomé Milpas Altas', 8993, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (55, 'San Lucas Sacatepéquez', 29902, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (56, 'Santa Lucía Milpas Altas', 18253, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (57, 'Magdalena Milpas Altas', 13016, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (58, 'Santa María de Jesús', 27622, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (59, 'Ciudad Vieja', 43690, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (60, 'San Miguel Dueñas', 16541, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (61, 'San Juan Alotenango', 29114, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (62, 'San Antonio Aguas Calientes', 13562, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (63, 'Santa Catarina Barahona', 4834, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (64, 'Chimaltenango', 120412, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (65, 'San José Poaquil', 34855, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (66, 'San Martín Jilotepeque', 97571, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (67, 'San Juan Comalapa', 63476, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (68, 'Santa Apolonia', 24299, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (69, 'Tecpán Guatemala', 116725, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (70, 'Patzún', 73932, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (71, 'San Miguel Pochuta', 11491, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (72, 'Patzicía', 42277, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (73, 'Santa Cruz Balanyá', 11302, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (74, 'Acatenango', 29473, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (75, 'San Pedro Yepocapa', 44659, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (76, 'San Andrés Itzapa', 36550, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (77, 'Parramos', 21570, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (78, 'Zaragoza', 30807, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (79, 'El Tejar', 24947, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (80, 'Escuintla', 174328, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (81, 'Santa Lucía Cotzumalguapa', 131225, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (82, 'La Democracia', 26299, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (83, 'Siquinalá', 26975, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (84, 'Masagua', 49600, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (85, 'Tiquisate', 65116, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (86, 'La Gomera', 55388, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (87, 'Guanagazapa', 17681, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (88, 'San José', 70283, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (89, 'Iztapa', 20984, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (90, 'Palín', 74201, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (91, 'San Vicente Pacaya', 18891, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (92, 'Nueva Concepción', 84096, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (93, 'Sipacate', 18959, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (94, 'Cuilapa', 48360, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (95, 'Barberena', 63086, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (96, 'Santa Rosa de Lima', 22306, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (97, 'Casillas', 26684, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (98, 'San Rafael Las Flores', 14530, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (99, 'Oratorio', 28375, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (100, 'San Juan Tecuaco', 13498, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (101, 'Chiquimulilla', 67719, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (102, 'Taxisco', 38630, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (103, 'Santa María Ixhuatán', 27143, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (104, 'Guazacapán', 23037, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (105, 'Santa Cruz Naranjo', 18782, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (106, 'Pueblo Nuevo Viñas', 29751, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (107, 'Nueva Santa Rosa', 40118, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (108, 'Sololá', 102208, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (109, 'San José Chacayá', 5491, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (110, 'Santa María Visitación', 2718, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (111, 'Santa Lucía Utatlán', 22064, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (112, 'Nahualá', 99796, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (113, 'Santa Catarina Ixtahuacán', 64451, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (114, 'Santa Clara La Laguna', 10763, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (115, 'Concepción', 7562, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (116, 'San Andrés Semetabaj', 15531, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (117, 'Panajachel', 16903, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (118, 'Santa Catarina Palopó', 5008, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (119, 'San Antonio Palopó', 16085, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (120, 'San Lucas Tolimán', 32465, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (121, 'Santa Cruz La Laguna', 8122, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (122, 'San Pablo La Laguna', 8184, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (123, 'San Marcos La Laguna', 3044, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (124, 'San Juan La Laguna', 14260, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (125, 'San Pedro La Laguna', 12528, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (126, 'Santiago Atitlán', 47407, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (127, 'Totonicapán', 123211, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (128, 'San Cristóbal Totonicapán', 44626, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (129, 'San Francisco El Alto', 69233, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (130, 'San Andrés Xecul', 31304, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (131, 'Momostenango', 147439, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (132, 'Santa María Chiquimula', 59961, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (133, 'Santa Lucía la Reforma', 26240, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (134, 'San Bartolo Aguas Calientes', 12742, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (135, 'Quetzaltenango', 211118, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (136, 'Salcajá', 22244, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (137, 'San Juan Olintepeque', 40493, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (138, 'San Carlos Sija', 37097, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (139, 'Sibilia', 9367, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (140, 'Cabricán', 28910, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (141, 'Cajolá', 19757, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (142, 'San Miguel Siguilá', 10119, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (143, 'San Juan Ostuncalco', 62282, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (144, 'San Mateo', 9209, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (145, 'Concepción Chiquirichapa', 21573, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (146, 'San Martín Sacatepéquez', 34847, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (147, 'Almolonga', 17918, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (148, 'Cantel', 48751, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (149, 'Huitán', 15175, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (150, 'Zunil', 16344, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (151, 'Colomba Costa Cuca', 57743, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (152, 'San Francisco La Unión', 9953, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (153, 'El Palmar', 32419, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (154, 'Coatepeque', 123894, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (155, 'Génova', 47403, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (156, 'Flores Costa Cuca', 25929, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (157, 'La Esperanza', 25657, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (158, 'Palestina de Los Altos', 21169, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (159, 'Mazatenango', 84971, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (160, 'Cuyotenango', 39280, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (161, 'San Francisco Zapotitlán', 26204, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (162, 'San Bernardino', 17995, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (163, 'San José el Ídolo', 12455, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (164, 'Santo Domingo Suchitepéquez', 50717, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (165, 'San Lorenzo', 14272, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (166, 'Samayac', 27525, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (167, 'San Pablo Jocopilas', 23835, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (168, 'San Antonio Suchitepéquez', 68692, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (169, 'San Miguel Panán', 13125, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (170, 'San Gabriel', 8442, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (171, 'Chicacao', 69300, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (172, 'Patulul', 43194, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (173, 'Santa Bárbara', 28096, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (174, 'San Juan Bautista', 9842, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (175, 'Santo Tomas La Unión', 13501, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (176, 'Zunilito', 9349, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (177, 'Pueblo Nuevo', 12483, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (178, 'Río Bravo', 32893, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (179, 'San José La Máquina', 27092, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (180, 'Retalhuleu', 114320, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (181, 'San Sebastián', 31486, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (182, 'Santa Cruz Muluá', 17031, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (183, 'San Martín Zapotitlán', 13614, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (184, 'San Felipe', 27953, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (185, 'San Andrés Villa Seca', 58763, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (186, 'Champerico', 40196, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (187, 'Nuevo San Carlos', 43214, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (188, 'El Asintal', 45253, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (189, 'San Marcos', 50800, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (190, 'San Pedro Sacatepéquez', 89692, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (191, 'San Antonio Sacatepéquez', 22193, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (192, 'Comitancillo', 82890, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (193, 'San Miguel Ixtahuacán', 53914, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (194, 'Concepción Tutuapa', 88046, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (195, 'Tacaná', 84339, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (196, 'Sibinal', 17615, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (197, 'Tajumulco', 66749, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (198, 'Tejutla', 47243, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (199, 'San Rafael Pie de la Cuesta', 19044, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (200, 'Nuevo Progreso', 33417, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (201, 'El Tumbador', 54764, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (202, 'San José el Rodeo', 20399, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (203, 'Malacatán', 112956, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (204, 'Catarina', 33891, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (205, 'Ayutla', 49118, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (206, 'Ocós', 13385, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (207, 'San Pablo', 55221, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (208, 'El Quetzal', 26743, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (209, 'La Reforma', 24718, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (210, 'Pajapita', 23627, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (211, 'Ixchiguán', 25994, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (212, 'San José Ojetenam', 23369, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (213, 'San Cristóbal Cucho', 18526, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (214, 'Sipacapa', 28921, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (215, 'Esquipulas Palo Gordo', 14711, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (216, 'Río Blanco', 6310, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (217, 'San Lorenzo', 14967, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (218, 'La Blanca', 35942, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (219, 'Huehuetenango', 143954, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (220, 'Chiantla', 95796, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (221, 'Malacatancito', 23858, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (222, 'Cuilco', 69329, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (223, 'Nentón', 53362, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (224, 'San Pedro Necta', 42565, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (225, 'Jacaltenango', 46794, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (226, 'San Pedro Soloma', 67936, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (227, 'San Ildefonso Ixtahuacán', 58592, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (228, 'Santa Bárbara', 46902, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (229, 'La Libertad', 51397, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (230, 'La Democracia', 63091, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (231, 'San Miguel Acatán', 37479, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (232, 'San Rafael La Independencia', 19216, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (233, 'Todos Santos Cuchumatán', 40927, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (234, 'San Juan Atitán', 26938, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (235, 'Santa Eulalia', 53589, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (236, 'San Mateo Ixtatán', 63139, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (237, 'Colotenango', 45954, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (238, 'San Sebastián Huehuetenango', 45444, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (239, 'Tectitán', 12201, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (240, 'Concepción Huista', 22016, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (241, 'San Juan Ixcoy', 31912, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (242, 'San Antonio Huista', 20313, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (243, 'San Sebastián Coatán', 26491, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (244, 'Santa Cruz Barillas', 133295, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (245, 'Aguacatán', 61209, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (246, 'San Rafael Petzal', 13231, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (247, 'San Gaspar Ixchil', 10801, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (248, 'Santiago Chimaltenango', 15283, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (249, 'Santa Ana Huista', 11126, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (250, 'Unión Cantinil', 19352, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (251, 'Petatán', 7409, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (252, 'Santa Cruz del Quiché', 103888, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (253, 'Chiché', 32897, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (254, 'Chinique', 14302, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (255, 'Zacualpa', 42188, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (256, 'Chajul', 55481, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (257, 'Santo Tomás Chichicastenango', 156681, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (258, 'Patzité', 8230, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (259, 'San Antonio Ilotenango', 33080, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (260, 'San Pedro Jocopilas', 39664, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (261, 'Cunén', 49935, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (262, 'San Juan Cotzal', 38330, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (263, 'Joyabaj', 116004, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (264, 'Santa María Nebaj', 81532, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (265, 'San Andrés Sajcabajá', 29257, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (266, 'San Miguel Uspantán', 78060, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (267, 'Sacapulas', 56954, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (268, 'San Bartolomé Jocotenango', 16326, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (269, 'Canillá', 13206, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (270, 'Chicamán', 45511, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (271, 'Playa Grande Ixcán', 115635, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (272, 'Pachalum', 10616, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (273, 'Salamá', 75654, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (274, 'San Miguel Chicaj', 39723, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (275, 'Rabinal', 47714, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (276, 'Cubulco', 61806, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (277, 'Granados', 15181, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (278, 'Santa Cruz El Chol', 11086, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (279, 'San Jerónimo', 30535, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (280, 'Purulhá', 68379, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (281, 'Cobán', 241927, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (282, 'Santa Cruz Verapaz', 38557, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (283, 'San Cristóbal Verapaz', 84321, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (284, 'Tactic', 43949, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (285, 'Tamahú', 26126, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (286, 'San Miguel Tucurú', 53484, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (287, 'Panzós', 84712, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (288, 'Senahú', 102683, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (289, 'San Pedro Carchá', 273204, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (290, 'San Juan Chamelco', 65375, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (291, 'San Agustín Lanquín', 27776, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (292, 'Santa María Cahabón', 73803, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (293, 'Chisec', 111182, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (294, 'Chahal', 31454, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (295, 'Fray Bartolomé de Las Casas', 83255, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (296, 'Santa Catalina La Tinta', 48405, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (297, 'Raxruhá', 42219, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (298, 'Flores', 46401, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (299, 'San José', 7385, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (300, 'San Benito', 55941, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (301, 'San Andrés', 36082, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (302, 'La Libertad', 88972, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (303, 'San Francisco', 17230, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (304, 'Santa Ana', 25269, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (305, 'Dolores', 30795, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (306, 'San Luis', 78604, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (307, 'Sayaxché', 102547, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (308, 'Melchor de Mencos', 31331, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (309, 'Poptún', 72109, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (310, 'Las Cruces', 40460, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (311, 'El Chal', 15808, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (312, 'Puerto Barrios', 114711, 18);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (313, 'Livingston', 83357, 18);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (314, 'El Estor', 86288, 18);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (315, 'Morales', 111730, 18);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (316, 'Los Amates', 67699, 18);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (317, 'Zacapa', 68738, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (318, 'Estanzuela', 10957, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (319, 'Río Hondo', 24547, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (320, 'Gualán', 50763, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (321, 'Teculután', 21070, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (322, 'Usumatlán', 13743, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (323, 'Cabañas', 15331, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (324, 'San Diego', 7956, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (325, 'La Unión', 39198, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (326, 'Huité', 12281, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (327, 'San Jorge', 13997, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (328, 'Chiquimula', 123844, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (329, 'San José La Arada', 9412, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (330, 'San Juan Ermita', 19430, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (331, 'Jocotán', 78144, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (332, 'Camotán', 63084, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (333, 'Olopa', 31276, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (334, 'Esquipulas', 57974, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (335, 'Concepción Las Minas', 12722, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (336, 'Quezaltepeque', 30913, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (337, 'San Jacinto', 13643, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (338, 'Ipala', 24625, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (339, 'Jalapa', 197894, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (340, 'San Pedro Pinula', 80930, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (341, 'San Luis Jilotepeque', 27733, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (342, 'San Manuel Chaparrón', 9348, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (343, 'San Carlos Alzatate', 22583, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (344, 'Monjas', 32787, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (345, 'Mataquescuintla', 48972, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (346, 'Jutiapa', 170481, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (347, 'El Progreso', 26503, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (348, 'Santa Catarina Mita', 32629, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (349, 'Agua Blanca', 18219, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (350, 'Asunción Mita', 54720, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (351, 'Yupiltepeque', 18575, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (352, 'Atescatempa', 20563, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (353, 'Jerez', 7107, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (354, 'El Adelanto', 8518, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (355, 'Zapotitlán', 10810, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (356, 'Comapa', 37917, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (357, 'Jalpatagua', 32112, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (358, 'Conguaco', 30669, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (359, 'Moyuta', 51134, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (360, 'Pasaco', 11402, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (361, 'San José Acatempa', 14095, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (362, 'Quesada', 24214, 22);