USE [violencia-db]

INSERT INTO territory (territory_id, name, population, parent_id) VALUES (1, N'Guatemala', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (2, N'El Progreso', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (3, N'Sacatepéquez', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (4, N'Chimaltenango', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (5, N'Escuintla', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (6, N'Santa Rosa', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (7, N'Sololá', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (8, N'Totonicapán', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (9, N'Quetzaltenango', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (10, N'Suchitepéquez', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (11, N'Retalhuleu', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (12, N'San Marcos', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (13, N'Huehuetenango', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (14, N'Quiché', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (15, N'Baja Verapaz', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (16, N'Alta Verapaz', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (17, N'Petén', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (18, N'Izabal', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (19, N'Zacapa', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (20, N'Chiquimula', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (21, N'Jalapa', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (22, N'Jutiapa', 0, null);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (23, N'Guatemala', 1229215, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (24, N'Santa Catarina Pinula', 88047, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (25, N'San José Pinula', 90835, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (26, N'San José del Golfo', 8545, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (27, N'Palencia', 75417, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (28, N'Chinautla', 126289, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (29, N'San Pedro Ayampuc', 69948, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (30, N'Mixco', 538189, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (31, N'San Pedro Sacatepéquez', 58175, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (32, N'San Juan Sacatepéquez', 291199, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (33, N'San Raymundo', 39162, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (34, N'Chuarrancho', 17436, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (35, N'Fraijanes', 65302, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (36, N'Amatitlán', 156177, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (37, N'Villa Nueva', 501127, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (38, N'Villa Canales', 169534, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (39, N'San Miguel Petapa', 154729, 1);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (40, N'Guastatoya', 27803, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (41, N'Morazán', 12736, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (42, N'San Agustín Acasaguastlán', 56428, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (43, N'San Cristóbal Acasaguastlán', 8055, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (44, N'El Jícaro', 13539, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (45, N'Sansare', 13812, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (46, N'Sanarate', 42840, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (47, N'San Antonio La Paz', 22916, 2);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (48, N'Antigua Guatemala', 61360, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (49, N'Jocotenango', 24463, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (50, N'Pastores', 20445, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (51, N'Sumpango', 48564, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (52, N'Santo Domingo Xenacoj', 15476, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (53, N'Santiago Sacatepéquez', 38667, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (54, N'San Bartolomé Milpas Altas', 8993, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (55, N'San Lucas Sacatepéquez', 29902, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (56, N'Santa Lucía Milpas Altas', 18253, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (57, N'Magdalena Milpas Altas', 13016, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (58, N'Santa María de Jesús', 27622, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (59, N'Ciudad Vieja', 43690, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (60, N'San Miguel Dueñas', 16541, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (61, N'San Juan Alotenango', 29114, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (62, N'San Antonio Aguas Calientes', 13562, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (63, N'Santa Catarina Barahona', 4834, 3);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (64, N'Chimaltenango', 120412, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (65, N'San José Poaquil', 34855, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (66, N'San Martín Jilotepeque', 97571, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (67, N'San Juan Comalapa', 63476, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (68, N'Santa Apolonia', 24299, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (69, N'Tecpán Guatemala', 116725, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (70, N'Patzún', 73932, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (71, N'San Miguel Pochuta', 11491, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (72, N'Patzicía', 42277, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (73, N'Santa Cruz Balanyá', 11302, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (74, N'Acatenango', 29473, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (75, N'San Pedro Yepocapa', 44659, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (76, N'San Andrés Itzapa', 36550, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (77, N'Parramos', 21570, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (78, N'Zaragoza', 30807, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (79, N'El Tejar', 24947, 4);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (80, N'Escuintla', 174328, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (81, N'Santa Lucía Cotzumalguapa', 131225, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (82, N'La Democracia', 26299, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (83, N'Siquinalá', 26975, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (84, N'Masagua', 49600, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (85, N'Tiquisate', 65116, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (86, N'La Gomera', 55388, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (87, N'Guanagazapa', 17681, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (88, N'San José', 70283, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (89, N'Iztapa', 20984, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (90, N'Palín', 74201, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (91, N'San Vicente Pacaya', 18891, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (92, N'Nueva Concepción', 84096, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (93, N'Sipacate', 18959, 5);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (94, N'Cuilapa', 48360, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (95, N'Barberena', 63086, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (96, N'Santa Rosa de Lima', 22306, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (97, N'Casillas', 26684, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (98, N'San Rafael Las Flores', 14530, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (99, N'Oratorio', 28375, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (100, N'San Juan Tecuaco', 13498, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (101, N'Chiquimulilla', 67719, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (102, N'Taxisco', 38630, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (103, N'Santa María Ixhuatán', 27143, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (104, N'Guazacapán', 23037, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (105, N'Santa Cruz Naranjo', 18782, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (106, N'Pueblo Nuevo Viñas', 29751, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (107, N'Nueva Santa Rosa', 40118, 6);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (108, N'Sololá', 102208, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (109, N'San José Chacayá', 5491, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (110, N'Santa María Visitación', 2718, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (111, N'Santa Lucía Utatlán', 22064, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (112, N'Nahualá', 99796, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (113, N'Santa Catarina Ixtahuacán', 64451, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (114, N'Santa Clara La Laguna', 10763, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (115, N'Concepción', 7562, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (116, N'San Andrés Semetabaj', 15531, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (117, N'Panajachel', 16903, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (118, N'Santa Catarina Palopó', 5008, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (119, N'San Antonio Palopó', 16085, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (120, N'San Lucas Tolimán', 32465, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (121, N'Santa Cruz La Laguna', 8122, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (122, N'San Pablo La Laguna', 8184, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (123, N'San Marcos La Laguna', 3044, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (124, N'San Juan La Laguna', 14260, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (125, N'San Pedro La Laguna', 12528, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (126, N'Santiago Atitlán', 47407, 7);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (127, N'Totonicapán', 123211, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (128, N'San Cristóbal Totonicapán', 44626, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (129, N'San Francisco El Alto', 69233, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (130, N'San Andrés Xecul', 31304, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (131, N'Momostenango', 147439, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (132, N'Santa María Chiquimula', 59961, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (133, N'Santa Lucía la Reforma', 26240, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (134, N'San Bartolo Aguas Calientes', 12742, 8);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (135, N'Quetzaltenango', 211118, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (136, N'Salcajá', 22244, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (137, N'San Juan Olintepeque', 40493, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (138, N'San Carlos Sija', 37097, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (139, N'Sibilia', 9367, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (140, N'Cabricán', 28910, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (141, N'Cajolá', 19757, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (142, N'San Miguel Siguilá', 10119, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (143, N'San Juan Ostuncalco', 62282, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (144, N'San Mateo', 9209, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (145, N'Concepción Chiquirichapa', 21573, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (146, N'San Martín Sacatepéquez', 34847, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (147, N'Almolonga', 17918, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (148, N'Cantel', 48751, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (149, N'Huitán', 15175, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (150, N'Zunil', 16344, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (151, N'Colomba Costa Cuca', 57743, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (152, N'San Francisco La Unión', 9953, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (153, N'El Palmar', 32419, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (154, N'Coatepeque', 123894, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (155, N'Génova', 47403, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (156, N'Flores Costa Cuca', 25929, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (157, N'La Esperanza', 25657, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (158, N'Palestina de Los Altos', 21169, 9);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (159, N'Mazatenango', 84971, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (160, N'Cuyotenango', 39280, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (161, N'San Francisco Zapotitlán', 26204, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (162, N'San Bernardino', 17995, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (163, N'San José el Ídolo', 12455, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (164, N'Santo Domingo Suchitepéquez', 50717, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (165, N'San Lorenzo', 14272, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (166, N'Samayac', 27525, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (167, N'San Pablo Jocopilas', 23835, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (168, N'San Antonio Suchitepéquez', 68692, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (169, N'San Miguel Panán', 13125, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (170, N'San Gabriel', 8442, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (171, N'Chicacao', 69300, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (172, N'Patulul', 43194, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (173, N'Santa Bárbara', 28096, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (174, N'San Juan Bautista', 9842, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (175, N'Santo Tomas La Unión', 13501, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (176, N'Zunilito', 9349, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (177, N'Pueblo Nuevo', 12483, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (178, N'Río Bravo', 32893, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (179, N'San José La Máquina', 27092, 10);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (180, N'Retalhuleu', 114320, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (181, N'San Sebastián', 31486, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (182, N'Santa Cruz Muluá', 17031, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (183, N'San Martín Zapotitlán', 13614, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (184, N'San Felipe', 27953, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (185, N'San Andrés Villa Seca', 58763, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (186, N'Champerico', 40196, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (187, N'Nuevo San Carlos', 43214, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (188, N'El Asintal', 45253, 11);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (189, N'San Marcos', 50800, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (190, N'San Pedro Sacatepéquez', 89692, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (191, N'San Antonio Sacatepéquez', 22193, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (192, N'Comitancillo', 82890, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (193, N'San Miguel Ixtahuacán', 53914, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (194, N'Concepción Tutuapa', 88046, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (195, N'Tacaná', 84339, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (196, N'Sibinal', 17615, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (197, N'Tajumulco', 66749, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (198, N'Tejutla', 47243, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (199, N'San Rafael Pie de la Cuesta', 19044, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (200, N'Nuevo Progreso', 33417, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (201, N'El Tumbador', 54764, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (202, N'San José el Rodeo', 20399, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (203, N'Malacatán', 112956, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (204, N'Catarina', 33891, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (205, N'Ayutla', 49118, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (206, N'Ocós', 13385, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (207, N'San Pablo', 55221, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (208, N'El Quetzal', 26743, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (209, N'La Reforma', 24718, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (210, N'Pajapita', 23627, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (211, N'Ixchiguán', 25994, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (212, N'San José Ojetenam', 23369, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (213, N'San Cristóbal Cucho', 18526, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (214, N'Sipacapa', 28921, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (215, N'Esquipulas Palo Gordo', 14711, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (216, N'Río Blanco', 6310, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (217, N'San Lorenzo', 14967, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (218, N'La Blanca', 35942, 12);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (219, N'Huehuetenango', 143954, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (220, N'Chiantla', 95796, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (221, N'Malacatancito', 23858, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (222, N'Cuilco', 69329, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (223, N'Nentón', 53362, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (224, N'San Pedro Necta', 42565, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (225, N'Jacaltenango', 46794, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (226, N'San Pedro Soloma', 67936, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (227, N'San Ildefonso Ixtahuacán', 58592, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (228, N'Santa Bárbara', 46902, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (229, N'La Libertad', 51397, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (230, N'La Democracia', 63091, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (231, N'San Miguel Acatán', 37479, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (232, N'San Rafael La Independencia', 19216, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (233, N'Todos Santos Cuchumatán', 40927, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (234, N'San Juan Atitán', 26938, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (235, N'Santa Eulalia', 53589, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (236, N'San Mateo Ixtatán', 63139, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (237, N'Colotenango', 45954, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (238, N'San Sebastián Huehuetenango', 45444, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (239, N'Tectitán', 12201, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (240, N'Concepción Huista', 22016, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (241, N'San Juan Ixcoy', 31912, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (242, N'San Antonio Huista', 20313, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (243, N'San Sebastián Coatán', 26491, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (244, N'Santa Cruz Barillas', 133295, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (245, N'Aguacatán', 61209, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (246, N'San Rafael Petzal', 13231, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (247, N'San Gaspar Ixchil', 10801, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (248, N'Santiago Chimaltenango', 15283, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (249, N'Santa Ana Huista', 11126, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (250, N'Unión Cantinil', 19352, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (251, N'Petatán', 7409, 13);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (252, N'Santa Cruz del Quiché', 103888, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (253, N'Chiché', 32897, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (254, N'Chinique', 14302, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (255, N'Zacualpa', 42188, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (256, N'Chajul', 55481, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (257, N'Santo Tomás Chichicastenango', 156681, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (258, N'Patzité', 8230, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (259, N'San Antonio Ilotenango', 33080, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (260, N'San Pedro Jocopilas', 39664, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (261, N'Cunén', 49935, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (262, N'San Juan Cotzal', 38330, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (263, N'Joyabaj', 116004, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (264, N'Santa María Nebaj', 81532, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (265, N'San Andrés Sajcabajá', 29257, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (266, N'San Miguel Uspantán', 78060, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (267, N'Sacapulas', 56954, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (268, N'San Bartolomé Jocotenango', 16326, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (269, N'Canillá', 13206, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (270, N'Chicamán', 45511, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (271, N'Playa Grande Ixcán', 115635, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (272, N'Pachalum', 10616, 14);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (273, N'Salamá', 75654, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (274, N'San Miguel Chicaj', 39723, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (275, N'Rabinal', 47714, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (276, N'Cubulco', 61806, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (277, N'Granados', 15181, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (278, N'Santa Cruz El Chol', 11086, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (279, N'San Jerónimo', 30535, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (280, N'Purulhá', 68379, 15);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (281, N'Cobán', 241927, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (282, N'Santa Cruz Verapaz', 38557, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (283, N'San Cristóbal Verapaz', 84321, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (284, N'Tactic', 43949, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (285, N'Tamahú', 26126, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (286, N'San Miguel Tucurú', 53484, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (287, N'Panzós', 84712, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (288, N'Senahú', 102683, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (289, N'San Pedro Carchá', 273204, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (290, N'San Juan Chamelco', 65375, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (291, N'San Agustín Lanquín', 27776, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (292, N'Santa María Cahabón', 73803, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (293, N'Chisec', 111182, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (294, N'Chahal', 31454, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (295, N'Fray Bartolomé de Las Casas', 83255, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (296, N'Santa Catalina La Tinta', 48405, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (297, N'Raxruhá', 42219, 16);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (298, N'Flores', 46401, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (299, N'San José', 7385, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (300, N'San Benito', 55941, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (301, N'San Andrés', 36082, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (302, N'La Libertad', 88972, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (303, N'San Francisco', 17230, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (304, N'Santa Ana', 25269, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (305, N'Dolores', 30795, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (306, N'San Luis', 78604, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (307, N'Sayaxché', 102547, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (308, N'Melchor de Mencos', 31331, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (309, N'Poptún', 72109, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (310, N'Las Cruces', 40460, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (311, N'El Chal', 15808, 17);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (312, N'Puerto Barrios', 114711, 18);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (313, N'Livingston', 83357, 18);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (314, N'El Estor', 86288, 18);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (315, N'Morales', 111730, 18);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (316, N'Los Amates', 67699, 18);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (317, N'Zacapa', 68738, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (318, N'Estanzuela', 10957, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (319, N'Río Hondo', 24547, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (320, N'Gualán', 50763, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (321, N'Teculután', 21070, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (322, N'Usumatlán', 13743, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (323, N'Cabañas', 15331, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (324, N'San Diego', 7956, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (325, N'La Unión', 39198, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (326, N'Huité', 12281, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (327, N'San Jorge', 13997, 19);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (328, N'Chiquimula', 123844, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (329, N'San José La Arada', 9412, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (330, N'San Juan Ermita', 19430, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (331, N'Jocotán', 78144, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (332, N'Camotán', 63084, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (333, N'Olopa', 31276, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (334, N'Esquipulas', 57974, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (335, N'Concepción Las Minas', 12722, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (336, N'Quezaltepeque', 30913, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (337, N'San Jacinto', 13643, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (338, N'Ipala', 24625, 20);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (339, N'Jalapa', 197894, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (340, N'San Pedro Pinula', 80930, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (341, N'San Luis Jilotepeque', 27733, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (342, N'San Manuel Chaparrón', 9348, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (343, N'San Carlos Alzatate', 22583, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (344, N'Monjas', 32787, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (345, N'Mataquescuintla', 48972, 21);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (346, N'Jutiapa', 170481, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (347, N'El Progreso', 26503, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (348, N'Santa Catarina Mita', 32629, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (349, N'Agua Blanca', 18219, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (350, N'Asunción Mita', 54720, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (351, N'Yupiltepeque', 18575, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (352, N'Atescatempa', 20563, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (353, N'Jerez', 7107, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (354, N'El Adelanto', 8518, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (355, N'Zapotitlán', 10810, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (356, N'Comapa', 37917, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (357, N'Jalpatagua', 32112, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (358, N'Conguaco', 30669, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (359, N'Moyuta', 51134, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (360, N'Pasaco', 11402, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (361, N'San José Acatempa', 14095, 22);
INSERT INTO territory (territory_id, name, population, parent_id) VALUES (362, N'Quesada', 24214, 22);